# Generated by Django 4.2 on 2025-05-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TourClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("gender", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("dob", models.DateField()),
                ("nationality", models.CharField(max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
