# Generated by Django 4.2 on 2025-05-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toursclients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourclient",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tourclient",
            name="id_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tourclient",
            name="passport_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
