# Generated by Django 4.2 on 2025-05-20 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("toursclients", "0002_tourclient_active_tourclient_id_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TourOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(null=True, upload_to="tour_offers/")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("per_what", models.CharField(max_length=255)),
                ("ends_on", models.DateField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
                ("content", models.TextField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("SMS", "SMS"),
                            ("WhatsApp", "WhatsApp"),
                            ("Email", "Email"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("Birthday", "Birthday"),
                            ("Holiday", "Holiday"),
                            ("Offer", "Offer"),
                        ],
                        max_length=255,
                    ),
                ),
                ("country", models.CharField(max_length=255, null=True)),
                ("holiday_name", models.CharField(max_length=255, null=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="toursclients.tourclient",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
