# Generated by Django 4.2 on 2025-05-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toursclients", "0003_touroffer_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="content",
        ),
        migrations.AddField(
            model_name="message",
            name="holiday_date",
            field=models.DateField(null=True),
        ),
    ]
