# Generated by Django 4.2 on 2025-07-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toursclients", "0004_remove_message_content_message_holiday_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tourclient",
            name="name",
        ),
        migrations.AddField(
            model_name="tourclient",
            name="first_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tourclient",
            name="last_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
