# Generated by Django 4.2 on 2025-07-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("toursclients", "0005_remove_tourclient_name_tourclient_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tourclient",
            name="last_name",
        ),
    ]
