# Generated by Django 4.2 on 2025-07-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toursclients", "0006_remove_tourclient_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourclient",
            name="last_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
