# Generated by Django 5.1.4 on 2025-01-15 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UnitListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
                ("property_name", models.CharField(max_length=255)),
                (
                    "listing_type",
                    models.CharField(
                        choices=[
                            ("Apartment", "Apartment"),
                            ("House", "House"),
                            ("AirBnB", "AirBnB"),
                            ("Room", "Room"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "listing_purpose",
                    models.CharField(
                        choices=[("For Sale", "For Sale"), ("For Rent", "For Rent")],
                        max_length=255,
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("1 Bedroom", "1 Bedroom"),
                            ("2 Bedroom", "2 Bedroom"),
                            ("3 Bedroom", "3 Bedroom"),
                            ("4 Bedroom", "4 Bedroom"),
                            ("5 Bedroom", "5 Bedroom"),
                            ("Studio", "Studio"),
                            ("Penthouse", "Penthouse"),
                            ("Duplex", "Duplex"),
                            ("Triplex", "Triplex"),
                            ("Quadruplex", "Quadruplex"),
                            ("Penthouse", "Penthouse"),
                        ],
                        max_length=255,
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit_price_currency",
                    models.CharField(
                        choices=[
                            ("USD", "USD"),
                            ("NGN", "NGN"),
                            ("EUR", "EUR"),
                            ("GBP", "GBP"),
                            ("CAD", "CAD"),
                            ("ZAR", "ZAR"),
                            ("KES", "KES"),
                            ("TZS", "TZS"),
                            ("UGX", "UGX"),
                            ("RWF", "RWF"),
                            ("XOF", "XOF"),
                        ],
                        default="KES",
                        max_length=255,
                    ),
                ),
                ("total_units", models.IntegerField(default=0)),
                ("available_units", models.IntegerField(default=0)),
                ("beds", models.IntegerField(default=0)),
                ("baths", models.IntegerField(default=0)),
                ("square_feet", models.IntegerField(default=0)),
                ("pets_allowed", models.BooleanField(default=False)),
                ("smoking_allowed", models.BooleanField(default=False)),
                ("parking_available", models.BooleanField(default=False)),
                ("security_available", models.BooleanField(default=False)),
                (
                    "security_deposit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "floor_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "unit_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("unit_description", models.TextField()),
                ("unit_image", models.ImageField(upload_to="listing_images/")),
                (
                    "unit_status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Not Available", "Not Available"),
                        ],
                        max_length=255,
                    ),
                ),
                ("views", models.IntegerField(default=0)),
                ("likes", models.IntegerField(default=0)),
                ("shares", models.IntegerField(default=0)),
                ("comments", models.IntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_trending", models.BooleanField(default=False)),
                ("is_new", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ListingInterestExpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.unitlisting",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ListingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
                ("image", models.ImageField(upload_to="listing_images/")),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.unitlisting",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.unitlisting",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
