# Generated by Django 5.1 on 2025-01-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitlisting',
            name='county',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unitlisting',
            name='town',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
