# Generated by Django 5.1 on 2025-01-17 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_unitlisting_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitlisting',
            name='electricity_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unitlisting',
            name='furnish_status',
            field=models.CharField(blank=True, choices=[('Fully Furnished', 'Fully Furnished'), ('Partially Furnished', 'Partially Furnished'), ('Unfurnished', 'Unfurnished'), ('Semi Furnished', 'Semi Furnished')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unitlisting',
            name='garbage_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unitlisting',
            name='gas_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unitlisting',
            name='gym',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unitlisting',
            name='internet_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unitlisting',
            name='kids_playground',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unitlisting',
            name='mininum_lease_period',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unitlisting',
            name='notice_period',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unitlisting',
            name='swimming_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unitlisting',
            name='water_included',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UnitAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('power_backup_available', models.BooleanField(default=False)),
                ('water_backup_available', models.BooleanField(default=False)),
                ('internet_available', models.BooleanField(default=False)),
                ('gym_available', models.BooleanField(default=False)),
                ('swimming_pool_available', models.BooleanField(default=False)),
                ('kids_playground_available', models.BooleanField(default=False)),
                ('security_available', models.BooleanField(default=False)),
                ('parking_available', models.BooleanField(default=False)),
                ('garbage_disposal_available', models.BooleanField(default=False)),
                ('gas_available', models.BooleanField(default=False)),
                ('laundry_available', models.BooleanField(default=False)),
                ('wheelchair_access', models.BooleanField(default=False)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('smoking_allowed', models.BooleanField(default=False)),
                ('elevator_available', models.BooleanField(default=False)),
                ('twenty_four_hour_security', models.BooleanField(default=False)),
                ('twenty_for_hour_water_supply', models.BooleanField(default=False)),
                ('cctv_available', models.BooleanField(default=False)),
                ('security_guard_available', models.BooleanField(default=False)),
                ('house_keeping_available', models.BooleanField(default=False)),
                ('maintenance_available', models.BooleanField(default=False)),
                ('backyard_available', models.BooleanField(default=False)),
                ('balcony_available', models.BooleanField(default=False)),
                ('garden_available', models.BooleanField(default=False)),
                ('rooftop_available', models.BooleanField(default=False)),
                ('unit_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='website.unitlisting')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
