# Generated by Django 5.1 on 2025-01-17 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_unitlisting_electricity_included_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnitAmenity',
        ),
    ]
