# Generated by Django 5.1 on 2025-01-17 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_delete_unitamenity"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitAmenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("available", models.BooleanField(default=False)),
                (
                    "unit_listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amenities",
                        to="website.unitlisting",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
