# Generated by Django 5.1 on 2025-01-17 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_unitamenity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitlisting',
            name='electricity_included',
        ),
        migrations.RemoveField(
            model_name='unitlisting',
            name='garbage_included',
        ),
        migrations.RemoveField(
            model_name='unitlisting',
            name='gas_included',
        ),
        migrations.RemoveField(
            model_name='unitlisting',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='unitlisting',
            name='internet_included',
        ),
        migrations.RemoveField(
            model_name='unitlisting',
            name='kids_playground',
        ),
        migrations.RemoveField(
            model_name='unitlisting',
            name='swimming_pool',
        ),
        migrations.RemoveField(
            model_name='unitlisting',
            name='water_included',
        ),
    ]
