# Generated by Django 5.1 on 2025-01-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_unitlisting_electricity_included_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitlisting',
            name='mininum_lease_period',
            field=models.CharField(choices=[('1 Month', '1 Month'), ('2 Months', '2 Months'), ('3 Months', '3 Months'), ('6 Months', '6 Months'), ('9 Months', '9 Months'), ('1 Year', '1 Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('4 Years', '4 Years'), ('5 Years', '5 Years')], default='1 Month', max_length=255),
        ),
        migrations.AlterField(
            model_name='unitlisting',
            name='notice_period',
            field=models.CharField(choices=[('1 Month', '1 Month'), ('2 Months', '2 Months'), ('3 Months', '3 Months'), ('4 Months', '4 Months'), ('5 Months', '5 Months')], default='1 Month', max_length=255),
        ),
    ]
