# Generated by Django 5.1 on 2025-01-18 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_unitlisting_location_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amenity',
        ),
    ]
