# Generated by Django 5.1 on 2025-01-18 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_clientrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('NGN', 'NGN'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('CAD', 'CAD'), ('ZAR', 'ZAR'), ('KES', 'KES'), ('TZS', 'TZS'), ('UGX', 'UGX'), ('RWF', 'RWF'), ('XOF', 'XOF')], default='KES', max_length=255)),
                ('description', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('lister_type', models.CharField(choices=[('Internal Agent', 'Internal Agent'), ('External Agent', 'External Agent'), ('Agency', 'Agency'), ('Owner', 'Owner')], max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.subscription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='unitlisting',
            name='lister',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='website.lister'),
        ),
    ]
