# Generated by Django 5.1 on 2025-01-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_subscription_lister_unitlisting_lister'),
    ]

    operations = [
        migrations.AddField(
            model_name='listinginterestexpression',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
