# Generated by Django 5.1 on 2025-01-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_listinginterestexpression_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitlisting',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
