# Generated by Django 5.1 on 2025-01-19 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0017_unitlisting_approved"),
    ]

    operations = [
        migrations.RenameField(
            model_name="unitlisting",
            old_name="mininum_lease_period",
            new_name="minimum_lease_period",
        ),
    ]
