# Generated by Django 5.1 on 2025-01-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "website",
            "0018_rename_mininum_lease_period_unitlisting_minimum_lease_period",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="listinginterestexpression",
            name="preferredContact",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
