# Generated by Django 5.1 on 2025-01-21 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_listinginterestexpression_preferredcontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listinginterestexpression',
            name='title',
        ),
    ]
