# Generated by Django 5.1 on 2025-01-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_lister_referral_code_unitlisting_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='looking_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='property_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='unit_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
