# Generated by Django 5.1 on 2025-01-23 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_clientrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientrequest',
            name='title',
        ),
    ]
