# Generated by Django 5.1 on 2025-01-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0029_listingimage_backup_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitlisting",
            name="listing_purpose",
            field=models.CharField(
                choices=[
                    ("For Sale", "For Sale"),
                    ("For Rent", "For Rent"),
                    ("For Lease", "For Lease"),
                ],
                max_length=255,
            ),
        ),
    ]
