# Generated by Django 5.1 on 2025-01-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_alter_unitlisting_listing_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitlisting',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unitlisting',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unitlisting',
            name='viewing_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
