# Generated by Django 5.1 on 2025-01-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_unitlisting_contact_name_unitlisting_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitlisting',
            name='viewing_fee',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
