# Generated by Django 5.1 on 2025-02-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0033_unitlisting_direct_contact_fee_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/%Y/%m/%d/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
