# Generated by Django 5.1 on 2025-02-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitlisting',
            name='unit_image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
