# Generated by Django 5.1 on 2025-03-04 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0036_listingcity_remove_unitlisting_county_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitlisting",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listingsincity",
                to="website.listingcity",
            ),
        ),
    ]
