# Generated by Django 5.1.4 on 2024-12-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_remove_property_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="phone_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
