# Generated by Django 5.1.4 on 2024-12-24 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_property_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="unit_rent",
        ),
    ]
