# Generated by Django 5.1.4 on 2024-12-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_propertyunit"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyunit",
            name="floor",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="propertyunit",
            name="unit_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
