# Generated by Django 5.1.4 on 2024-12-24 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_propertyunit_floor_propertyunit_unit_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyunit",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="propertyunits",
                to="properties.property",
            ),
        ),
    ]
