# Generated by Django 5.1.4 on 2024-12-24 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0007_alter_propertyunit_property"),
        ("tenants", "0002_tenantnextofkin"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyunit",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
    ]
