# Generated by Django 5.1.4 on 2024-12-28 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0009_alter_propertyunit_tenant"),
        ("tenants", "0003_remove_tenant_date_joined_tenant_move_in_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyunit",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenants.tenant",
            ),
        ),
    ]
