# Generated by Django 5.1.4 on 2024-12-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0010_alter_propertyunit_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyunit",
            name="size",
            field=models.FloatField(default=0),
        ),
    ]
