# Generated by Django 5.1.4 on 2024-12-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0011_propertyunit_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyunit",
            name="status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
