# Generated by Django 5.1.4 on 2024-12-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_propertyunit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyunit',
            name='floor',
            field=models.CharField(blank=True, default='1', max_length=255, null=True),
        ),
    ]
