# Generated by Django 5.1.4 on 2024-12-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0014_maintenancerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancerequest",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
