# Generated by Django 5.1.4 on 2024-12-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0015_maintenancerequest_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenancerequest",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
