# Generated by Django 5.1.4 on 2024-12-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_alter_property_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyunit',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
