# Generated by Django 5.1.4 on 2025-01-06 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0025_waterbill_month_waterbill_year"),
        ("tenants", "0006_alter_tenant_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="waterbill",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tenantwaterbills",
                to="tenants.tenant",
            ),
        ),
    ]
