# Generated by Django 5.1.4 on 2025-01-06 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0026_waterbill_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbill',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unitwaterbills', to='properties.propertyunit'),
        ),
    ]
