# Generated by Django 5.1.4 on 2025-01-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0028_waterbill_amount_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenancerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("In Progress", "IN_PROGRESS"),
                    ("Completed", "COMPLETED"),
                    ("Overdue", "OVERDUE"),
                    ("Pending", "PENDING"),
                    ("Partially Paid", "PARTIALLY_PAID"),
                ],
                default="Pending",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="waterbill",
            name="status",
            field=models.CharField(
                choices=[
                    ("In Progress", "IN_PROGRESS"),
                    ("Completed", "COMPLETED"),
                    ("Overdue", "OVERDUE"),
                    ("Pending", "PENDING"),
                    ("Partially Paid", "PARTIALLY_PAID"),
                ],
                default="Pending",
                max_length=255,
            ),
        ),
    ]
