# Generated by Django 5.1 on 2025-01-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0031_electricitybill_garbagebill'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbill',
            name='reading_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
