# Generated by Django 5.1 on 2025-02-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0034_property_garbage_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyunit',
            name='water_price',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
        ),
    ]
