# Generated by Django 5.1 on 2025-02-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0038_alter_waterbill_current_reading_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="waterbill",
            name="fully_paid",
            field=models.BooleanField(default=False),
        ),
    ]
