# Generated by Django 5.1 on 2025-02-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0040_remove_property_manager_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyunit',
            name='garbage_charge',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
