# Generated by Django 5.1 on 2025-02-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0042_remove_propertyunit_garbage_charge_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="waterbill",
            name="units_counsumed",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
