# Generated by Django 5.1 on 2025-02-25 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0043_waterbill_units_counsumed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="waterbill",
            old_name="units_counsumed",
            new_name="units_consumed",
        ),
    ]
