# Generated by Django 5.1 on 2025-03-06 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0044_rename_units_counsumed_waterbill_units_consumed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyunit',
            name='size',
        ),
    ]
