# Generated by Django 4.2 on 2025-05-17 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0046_alter_waterbill_amount_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waterbill",
            name="unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unitwaterbills",
                to="properties.propertyunit",
            ),
        ),
    ]
