# Generated by Django 5.1.7 on 2026-03-25 12:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0023_tenantpayment_security_deposit_payment"),
        ("properties", "0047_alter_waterbill_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="water_charge",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("250.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="waterbill",
            name="unit_bill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unitwaterbills",
                to="payments.unitmonthbill",
            ),
        ),
    ]
