# Generated by Django 5.1.7 on 2026-03-25 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0048_property_water_charge_alter_waterbill_unit_bill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenancerequest",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenancerequests",
                to="properties.property",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancerequest",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenancerequests",
                to="properties.propertyunit",
            ),
        ),
    ]
