# Generated by Django 5.1.7 on 2026-04-04 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0049_alter_maintenancerequest_property_and_more"),
        ("tenants", "0006_alter_tenant_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyunit",
            name="tenant",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tenantunit",
                to="tenants.tenant",
            ),
        ),
    ]
