# Generated by Django 5.1.7 on 2026-04-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0050_alter_propertyunit_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenancerequest",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="maintenance/"),
        ),
    ]
