# Generated by Django 5.1.7 on 2026-04-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0051_alter_maintenancerequest_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="address",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
