# Generated by Django 5.1.4 on 2025-01-05 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_year_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="month",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="months",
                to="core.year",
            ),
        ),
    ]
