# Generated by Django 4.2 on 2025-07-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_useraction"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraction",
            name="action_details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
