# Generated by Django 5.1.7 on 2026-03-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_useraction"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraction",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
