# Generated by Django 4.2 on 2025-07-10 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_useraction_action_details"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useraction",
            old_name="action",
            new_name="action_type",
        ),
    ]
