# Generated by Django 5.1.4 on 2024-12-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_tenantnextofkin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="date_joined",
        ),
        migrations.AddField(
            model_name="tenant",
            name="move_in_date",
            field=models.DateField(null=True),
        ),
    ]
