# Generated by Django 5.1.4 on 2024-12-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_tenant_lease_date_tenant_occupation_tenant_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="lease_duration",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="renews_every",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
