# Generated by Django 5.1.4 on 2025-01-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_lease_duration_tenant_renews_every'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenantnextofkin',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
