# Generated by Django 4.2 on 2025-04-29 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0046_alter_waterbill_amount_paid'),
        ('tenants', '0006_alter_tenant_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='unit_assigned',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_unit', to='properties.propertyunit'),
        ),
    ]
