# Generated by Django 4.2 on 2025-05-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0007_tenant_unit_assigned"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="lease_contract",
            field=models.FileField(null=True, upload_to="lease_contracts/"),
        ),
    ]
