# Generated by Django 4.2 on 2025-05-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0008_tenant_lease_contract"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="lease_contract",
            field=models.FileField(upload_to="lease_contracts"),
        ),
    ]
