# Generated by Django 5.1.4 on 2024-12-29 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_waterbill_amount'),
        ('tenants', '0005_tenant_lease_duration_tenant_renews_every'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbill',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant'),
        ),
    ]
