# Generated by Django 5.1.4 on 2025-01-07 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_expense'),
        ('properties', '0030_alter_maintenancerequest_status_and_more'),
        ('tenants', '0006_alter_tenant_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbillpayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'CASH'), ('M-Pesa', 'MPESA'), ('Bank Transfer', 'BANK_TRANSFER'), ('Bank Deposit', 'BANK_DEPOSIT')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('amount_expected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'CASH'), ('M-Pesa', 'MPESA'), ('Bank Transfer', 'BANK_TRANSFER'), ('Bank Deposit', 'BANK_DEPOSIT')], max_length=255, null=True)),
                ('payment_status', models.CharField(choices=[('Future', 'FUTURE'), ('Pending', 'PENDING'), ('Paid', 'PAID'), ('Overdue', 'OVERDUE'), ('Partially Paid', 'PARTIALLY_PAID')], default='Pending', max_length=255)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.propertyunit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
