# Generated by Django 5.1.4 on 2025-01-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_rentpayment_month_rentpayment_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentpayment",
            name="fully_paid",
            field=models.BooleanField(default=False),
        ),
    ]
