# Generated by Django 5.1.4 on 2024-12-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_tenantpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantpayment',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
