# Generated by Django 5.1.4 on 2025-01-07 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_month_is_active_alter_waterprice_is_active_and_more"),
        ("payments", "0005_rentpayment_fully_paid"),
        ("properties", "0030_alter_maintenancerequest_status_and_more"),
        ("tenants", "0006_alter_tenant_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rentpayment",
            name="amount_expected",
        ),
        migrations.RemoveField(
            model_name="rentpayment",
            name="fully_paid",
        ),
        migrations.RemoveField(
            model_name="rentpayment",
            name="month",
        ),
        migrations.RemoveField(
            model_name="rentpayment",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="rentpayment",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="rentpayment",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="rentpayment",
            name="year",
        ),
        migrations.CreateModel(
            name="RentBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "amount_expected",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Future", "FUTURE"),
                            ("Pending", "PENDING"),
                            ("Paid", "PAID"),
                            ("Overdue", "OVERDUE"),
                            ("Partially Paid", "PARTIALLY_PAID"),
                        ],
                        default="Pending",
                        max_length=255,
                    ),
                ),
                ("fully_paid", models.BooleanField(default=False)),
                (
                    "month",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.month",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="properties.propertyunit",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.year",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="rentpayment",
            name="rent_bill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.rentbill",
            ),
        ),
    ]
