# Generated by Django 5.1.4 on 2024-12-29 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_tenantpayment_reference'),
        ('properties', '0013_alter_propertyunit_floor'),
        ('tenants', '0005_tenant_lease_duration_tenant_renews_every'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantpayment',
            name='previous_balances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tenantpayment',
            name='water_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.waterbill'),
        ),
        migrations.CreateModel(
            name='RentBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('month', models.CharField(choices=[('January', 'JANUARY'), ('February', 'FEBRUARY'), ('March', 'MARCH'), ('April', 'APRIL'), ('May', 'MAY'), ('June', 'JUNE'), ('July', 'JULY'), ('August', 'AUGUST'), ('September', 'SEPTEMBER'), ('October', 'OCTOBER'), ('November', 'NOVEMBER'), ('December', 'DECEMBER')], max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Future', 'FUTURE'), ('Pending', 'PENDING'), ('Paid', 'PAID'), ('Overdue', 'OVERDUE')], default='Future', max_length=255)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentbills', to='tenants.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertyunit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tenantpayment',
            name='rent_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.rentbill'),
        ),
    ]
