# Generated by Django 5.1.4 on 2025-01-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_remove_rentpayment_amount_expected_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantpayment",
            name="payment_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="rentbill",
            name="status",
            field=models.CharField(
                choices=[
                    ("Future", "FUTURE"),
                    ("Pending", "PENDING"),
                    ("Paid", "PAID"),
                    ("Overdue", "OVERDUE"),
                    ("Partially Paid", "PARTIALLY_PAID"),
                    ("Cancelled", "CANCELLED"),
                    ("Completed", "COMPLETED"),
                ],
                default="Pending",
                max_length=255,
            ),
        ),
    ]
