# Generated by Django 5.1.4 on 2024-12-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_tenantpayment_previous_balances_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentbill',
            name='status',
            field=models.CharField(choices=[('Future', 'FUTURE'), ('Pending', 'PENDING'), ('Paid', 'PAID'), ('Overdue', 'OVERDUE'), ('Partially Paid', 'PARTIALLY_PAID')], default='Future', max_length=255),
        ),
        migrations.AlterField(
            model_name='tenantpayment',
            name='status',
            field=models.CharField(choices=[('Future', 'FUTURE'), ('Pending', 'PENDING'), ('Paid', 'PAID'), ('Overdue', 'OVERDUE'), ('Partially Paid', 'PARTIALLY_PAID')], default='Future', max_length=255),
        ),
    ]
