# Generated by Django 5.1.4 on 2024-12-30 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_rentbill_status_alter_tenantpayment_status'),
        ('properties', '0019_maintenancerequest_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantpayment',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.propertyunit'),
        ),
    ]
