# Generated by Django 5.1.4 on 2025-01-09 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_tenantpayment_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentpayment',
            name='rent_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenantrentpayments', to='payments.rentbill'),
        ),
    ]
