# Generated by Django 5.1.4 on 2024-12-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_tenantpayment_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantpayment',
            name='rent_amount',
        ),
        migrations.RemoveField(
            model_name='tenantpayment',
            name='water_amount',
        ),
    ]
