# Generated by Django 5.1.4 on 2024-12-30 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_remove_tenantpayment_rent_amount_and_more'),
        ('properties', '0019_maintenancerequest_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbill',
            name='previous_reading',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='waterbill',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unitwaterbills', to='properties.propertyunit'),
        ),
    ]
