# Generated by Django 5.1.4 on 2024-12-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_waterbill_previous_reading_alter_waterbill_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbill',
            name='status',
            field=models.CharField(choices=[('Future', 'FUTURE'), ('Pending', 'PENDING'), ('Paid', 'PAID'), ('Overdue', 'OVERDUE'), ('Partially Paid', 'PARTIALLY_PAID')], default='Pending', max_length=255),
        ),
    ]
