# Generated by Django 5.1 on 2025-02-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0012_garbagebill_garbagebillpayment_unitmonthbill_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitmonthbill",
            name="amount_expected",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
