# Generated by Django 5.1.4 on 2024-12-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_waterbill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbill',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
