# Generated by Django 5.1 on 2025-02-01 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_alter_unitmonthbill_amount_expected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbagebill',
            name='unit_bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.unitmonthbill'),
        ),
    ]
