# Generated by Django 5.1 on 2025-02-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0014_alter_garbagebill_unit_bill"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitmonthbill",
            name="notified",
            field=models.BooleanField(default=False),
        ),
    ]
