# Generated by Django 5.1 on 2025-02-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_unitmonthbill_garbage_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitmonthbill',
            name='fully_paid',
            field=models.BooleanField(default=False),
        ),
    ]
