# Generated by Django 5.1 on 2025-02-02 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0017_unitmonthbill_fully_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantpayment",
            name="garbage_bill_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.garbagebillpayment",
            ),
        ),
    ]
