# Generated by Django 5.1 on 2025-02-02 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0018_tenantpayment_garbage_bill_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentbill",
            name="unit_bill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.unitmonthbill",
            ),
        ),
    ]
