# Generated by Django 5.1 on 2025-02-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0020_tenantpayment_unit_bill"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitmonthbill",
            name="whatsapp_notification_sent",
            field=models.BooleanField(default=False),
        ),
    ]
