# Generated by Django 5.1.7 on 2026-03-31 09:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_useraction_description"),
        ("payments", "0023_tenantpayment_security_deposit_payment"),
        ("properties", "0049_alter_maintenancerequest_property_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryMonthBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "rent_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "water_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "garbage_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Future", "FUTURE"),
                            ("Pending", "PENDING"),
                            ("Paid", "PAID"),
                            ("Overdue", "OVERDUE"),
                            ("Partially Paid", "PARTIALLY_PAID"),
                            ("Cancelled", "CANCELLED"),
                            ("Completed", "COMPLETED"),
                        ],
                        default="Pending",
                        max_length=255,
                    ),
                ),
                (
                    "month",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.month",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.propertyunit",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.year",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
