# Generated by Django 5.1.7 on 2026-03-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0024_temporarymonthbill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temporarymonthbill",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Captured", "Captured"),
                    ("Confirmed", "Confirmed"),
                ],
                default="Pending",
                max_length=255,
            ),
        ),
    ]
