# Generated by Django 5.1.7 on 2026-03-31 09:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0025_alter_temporarymonthbill_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="temporarymonthbill",
            old_name="water_amount",
            new_name="current_reading",
        ),
        migrations.AddField(
            model_name="temporarymonthbill",
            name="previous_reading",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
