# Generated by Django 5.1.7 on 2026-04-04 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_useraction_description"),
        (
            "payments",
            "0026_rename_water_amount_temporarymonthbill_current_reading_and_more",
        ),
        ("properties", "0049_alter_maintenancerequest_property_and_more"),
        ("tenants", "0006_alter_tenant_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="garbagebill",
            name="unit_bill",
        ),
        migrations.RemoveField(
            model_name="temporarymonthbill",
            name="garbage_amount",
        ),
        migrations.RemoveField(
            model_name="tenantpayment",
            name="garbage_bill_payment",
        ),
        migrations.RemoveField(
            model_name="tenantpayment",
            name="rent_payment",
        ),
        migrations.RemoveField(
            model_name="tenantpayment",
            name="security_deposit_payment",
        ),
        migrations.RemoveField(
            model_name="tenantpayment",
            name="unit_bill",
        ),
        migrations.RemoveField(
            model_name="tenantpayment",
            name="water_bill_payment",
        ),
        migrations.AddField(
            model_name="garbagebill",
            name="month",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="garbagebills",
                to="core.month",
            ),
        ),
        migrations.AddField(
            model_name="garbagebill",
            name="year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="garbagebills",
                to="core.year",
            ),
        ),
        migrations.AddField(
            model_name="tenantpayment",
            name="reference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="garbagebill",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="garbagebills",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="garbagebill",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="garbagebills",
                to="properties.propertyunit",
            ),
        ),
        migrations.AlterField(
            model_name="tenantpayment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("General Payment", "General Payment"),
                    ("Rent", "Rent"),
                    ("Water Bill", "Water Bill"),
                    ("Garbage Bill", "Garbage Bill"),
                    ("Security Deposit", "Security Deposit"),
                    ("Other", "Other"),
                ],
                default="Rent",
                max_length=255,
            ),
        ),
    ]
