# Generated by Django 5.1.7 on 2026-04-04 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0027_remove_garbagebill_unit_bill_and_more"),
        ("properties", "0049_alter_maintenancerequest_property_and_more"),
        ("tenants", "0006_alter_tenant_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitmonthbill",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unitmonthbills",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="unitmonthbill",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unitmonthbills",
                to="properties.propertyunit",
            ),
        ),
    ]
