# Generated by Django 5.1 on 2025-01-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_id_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Landlord", "LANDLORD"),
                    ("Lister", "LISTER"),
                    ("Tenant", "TENANT"),
                ],
                default="Landlord",
                max_length=255,
            ),
        ),
    ]
