# Generated by Django 5.1 on 2025-01-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_firebase_uid_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Landlord", "LANDLORD"),
                    ("Lister", "LISTER"),
                    ("Tenant", "TENANT"),
                    ("Caretaker", "CARETAKER"),
                ],
                default="Landlord",
                max_length=255,
            ),
        ),
    ]
