# Generated by Django 5.1 on 2025-02-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="marital_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
