# Generated by Django 5.1 on 2025-02-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_housemanager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Landlord", "LANDLORD"),
                    ("Lister", "LISTER"),
                    ("Tenant", "TENANT"),
                    ("Caretaker", "CARETAKER"),
                    ("House Manager", "HOUSE_MANAGER"),
                ],
                default="Landlord",
                max_length=255,
            ),
        ),
    ]
