# Generated by Django 4.2 on 2025-07-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Landlord", "Landlord"),
                    ("Lister", "Lister"),
                    ("Tenant", "Tenant"),
                    ("Caretaker", "Caretaker"),
                    ("House Manager", "House Manager"),
                    ("Employee", "Employee"),
                ],
                default="Tenant",
                max_length=255,
            ),
        ),
    ]
