# Generated by Django 5.1 on 2025-01-28 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("website", "0030_alter_unitlisting_listing_purpose"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(max_length=3)),
                (
                    "payment_channel",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bank", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "country_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("paid_at", models.DateTimeField()),
                ("reference", models.CharField(max_length=255)),
                (
                    "payment_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "request_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "preferred_contact",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apis.customer"
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.unitlisting",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
